### ISSUE TITLE
This does not seem to work in Webstorm 2020.3

### ISSUE THREAD

**Issue by jeryldev** [ifahrentholz/webstorm-snippets#1]
This does not seem to work in Webstorm 2020.3. When I tried to import the live_templates.jar in webstorm 2020.3, the live templates does not seem to work.

**Comment by Lalit64** [comment]
> This does not seem to work in Webstorm 2020.3. When I tried to import the live_templates.jar in webstorm 2020.3, the live templates does not seem to work.

True Please Fix this issue

**Comment by ifahrentholz** [comment]
I'll check it

**Comment by ace3** [comment]
it's working on my side. Using Webstorm 2021.1

**Comment by Lalit64** [comment]
Ya now its working, Thanks Mate

**Comment by ifahrentholz** [comment]
Ok so I'll close this ticket now.

**Comment by Lalit64** [comment]
Oh hey I think they dont work anymore. Sorry about the inconvenience
